### ISSUE TITLE
AAF Rucksack bei NATO Autorifleman

### ISSUE THREAD

**Issue by Schwaggot** [Pergor/ADV_MissionTemplate#2]
Zweite Montagsmission bei der ein NATO Autorifleman einen AAF Rucksack (DigiCamo) bekommen hat, kA ob das so gewollt ist.

**Comment by Schwaggot** [comment]
![20170828201134_1](https://user-images.githubusercontent.com/23381725/29787019-9aff0630-8c2d-11e7-8908-9dea48797957.jpg)

**Comment by Pergor** [comment]
Ne, das ist noch ein Relikt von früher, das ich bei den bisherigen Fixes übersehen habe.

Kommt nicht wieder vor. ;)

**Comment by Pergor** [comment]
#9ecf19c

**Comment by Pergor** [comment]
Gefixt mit 9ecf19c
